apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: z48yknbf0-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:48670a9e8d58fa67677174d74e496faef677395c@sha256:523877bc7afa07da2933f516da2f81b3e11191aa313e66c0a4972f2c55bd5748
          name: container-image
